language: objective-c
osx_image: xcode7.3

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

matrix:
  include:
    - osx_image: xcode7.3
      env: SDK=appletvos9.2 OS=tvOS
#    - osx_image: xcode7.3
#      env: SDK=macosx OS=OSX
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator8.4 OS=iOS NAME="iPhone 4s"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator8.4 OS=iOS NAME="iPhone 5s"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator9.0 OS=iOS NAME="iPhone 4s"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator9.0 OS=iOS NAME="iPhone 5s"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator9.0 OS=iOS NAME="iPhone 6s"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator9.0 OS=iOS NAME="iPhone 6s Plus"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator9.0 OS=iOS NAME="iPad 2"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator9.0 OS=iOS NAME="iPad Pro"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator9.0 OS=iOS NAME="iPad Air"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator9.3 OS=iOS NAME="iPhone 4s"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator9.3 OS=iOS NAME="iPhone 5s"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator9.3 OS=iOS NAME="iPhone 6s"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator9.3 OS=iOS NAME="iPhone 6s Plus"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator9.3 OS=iOS NAME="iPad 2"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator9.3 OS=iOS NAME="iPad Pro"
#    - osx_image: xcode7.3
#      env: SDK=iphonesimulator9.3 OS=iOS NAME="iPad Air"

script: ./scripts/common.sh $OS $SDK $NAME
