language: objective-c
osx_image: xcode7.3

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool

matrix:
  include:
    - osx_image: xcode7.3
      env: R_SDK=macosx R_OS=OSX R_OS_VER=10.11 R_NAME="OS X"
    - osx_image: xcode7.3
      env: R_SDK=iphonesimulator9.3 R_OS=iOS R_OS_VER=9.3 R_NAME="iPhone 4s"
    - osx_image: xcode7.3
      env: R_SDK=iphonesimulator9.3 R_OS=iOS R_OS_VER=9.3 R_NAME="iPhone 6s"
    - osx_image: xcode7.3
      env: R_SDK=iphonesimulator9.3 R_OS=iOS R_OS_VER=9.3 R_NAME="iPad 2"
    - osx_image: xcode7.3
      env: R_SDK=iphonesimulator9.3 R_OS=iOS R_OS_VER=9.3 R_NAME="iPad Pro"
    - osx_image: xcode7.3
      env: R_SDK=iphonesimulator9.3 R_OS=iOS R_OS_VER=9.3 R_NAME="iPad Air"

script:
 - ./scripts/common.sh $R_OS $R_SDK $R_NAME $R_OS_VER
